services:
  app:
    image: "$IMAGE"
    network_mode: host
    deploy:
      replicas: 1
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.headless=true --server.enableCORS=false --server.enableWebsocketCompression=false

  nginx:
    container_name: nginx
    restart: always
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app