services:
  app:
    env_file:
      - .env
    image: $IMAGE
    deploy:
      replicas: 1
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --server.enableWebsocketCompression=false
    networks:
      - proxy_network


  nginx:
    container_name: nginx
    restart: always
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - proxy_network

#Docker Networks
networks:
  proxy_network:
    driver: bridge